name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Read mod version
        id: props
        run: echo "value=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Publish mod to GitHub Releases
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar

          name: Omni-Utils Release
          version: ${{ steps.props.outputs.value }}
          version-type: release

          loaders: |
            neoforge
          game-versions: |
            1.21.1

      - name: Get last commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=format:%s%n%b)" >> $GITHUB_OUTPUT

      - name: Notify Discord on Success
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ||<@&1119816316560359515><@&1179960869807988747><@&1203776983167803482><@&1203776907770859630>||
            # New Build of Omni-Utils ${{ steps.props.outputs.value }} for Neoforge 1.21.1 to be Balance/Bug Tested!
            **Changes:**  
            ${{ steps.commit.outputs.message }}
            ## [**__Download__**](https://github.com/LopyLuna/Omni-Utils/releases/download/${{ steps.props.outputs.value }}/omni_util-${{ steps.props.outputs.value }}.jar)